// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: breed.sql

package db

import (
	"context"
)

const createBreed = `-- name: CreateBreed :one

INSERT INTO breed (
                   breed_name
) VALUES (
           $1
) RETURNING breed_id, breed_name, created_at
`

func (q *Queries) CreateBreed(ctx context.Context, breedName string) (Breed, error) {
	row := q.db.QueryRowContext(ctx, createBreed, breedName)
	var i Breed
	err := row.Scan(&i.BreedID, &i.BreedName, &i.CreatedAt)
	return i, err
}
