// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"time"
)

type Breed struct {
	BreedID   int64     `json:"breed_id"`
	BreedName string    `json:"breed_name"`
	CreatedAt time.Time `json:"created_at"`
}

type Hatchery struct {
	HatcheryID  int64     `json:"hatchery_id"`
	Infertile   int64     `json:"infertile"`
	Early       int64     `json:"early"`
	Middle      int64     `json:"middle"`
	Late        int64     `json:"late"`
	DeadChicks  int64     `json:"dead_chicks"`
	AliveChicks int64     `json:"alive_chicks"`
	CreatedAt   time.Time `json:"created_at"`
}

type Premise struct {
	PremisesID int64     `json:"premises_id"`
	Farm       string    `json:"farm"`
	House      string    `json:"house"`
	CreatedAt  time.Time `json:"created_at"`
}

type Production struct {
	ProductionID int64     `json:"production_id"`
	Eggs         int64     `json:"eggs"`
	Dirty        int64     `json:"dirty"`
	WrongShape   int64     `json:"wrong_shape"`
	WeakShell    int64     `json:"weak_shell"`
	Damaged      int64     `json:"damaged"`
	HatchingEggs int64     `json:"hatching_eggs"`
	CreatedAt    time.Time `json:"created_at"`
}
