apiVersion: apps/v1

kind: Deployment

metadata:

  name: flock-manager-api-deployment

  labels:

    app: flock-manager-api

spec:

  replicas: 1

  selector:

    matchLabels:

      app: flock-manager-api

  template:

    metadata:

      labels:

        app: flock-manager-api

    spec:

      containers:

        - name: flock-manager-api

          image: 708577282797.dkr.ecr.af-south-1.amazonaws.com/flockmanager:a187466ddf3b951afbd4abe901e4ec23af05c781

          ports:

            - containerPort: 8080
