apiVersion: v1
kind: Service
metadata:
  name: flock-manager-api-service
spec:
  selector:
    app: flock-manager-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer